# Generated by Django 2.2 on 2019-04-08 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_to',
        ),
        migrations.AlterField(
            model_name='task',
            name='creat_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 8, 23, 51, 26, 738907)),
        ),
    ]
